### PR TITLE
Dropping stringmap and asynquence

### LINKED ISSUE #1: Remove asynquence
Perhaps `run-parallel`, `run-series`, or `async-each` would be a good replacement?

### PR DESCRIPTION
**Pull request by TehShrike**
and swapping extend for xtend

Fixes #1

Look this one over closely @artskydj, if there's an edge case in there, it's going to bite later.

### CODE REVIEW

**Comment by ArtskydJ** [comment]
I looked over this for a while, and nothing popped out at me...

**Comment by TehShrike** [comment]
aaaah!

**Comment by TehShrike** [comment]
Published as 2.1.0

**Comment by TehShrike** [comment]
Looks like noddity-butler's tests all pass too, which is nice

**Pull request merged**
